# Generated by Django 6.0.3 on 2026-04-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Docente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="docentes/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Licenciatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("duracao", models.IntegerField()),
                ("urlSite", models.CharField(max_length=255)),
                ("objetivos", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="UnidadeCurricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("ano", models.IntegerField()),
                ("semestre", models.IntegerField()),
                ("ects", models.IntegerField()),
                ("apresentacao", models.TextField()),
                ("programa", models.TextField()),
                (
                    "docentes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="unidadesCurriculares",
                        to="portfolio.docente",
                    ),
                ),
                (
                    "licenciaturas",
                    models.ManyToManyField(
                        blank=True,
                        related_name="unidadesCurriculares",
                        to="portfolio.licenciatura",
                    ),
                ),
            ],
        ),
    ]
