# Generated by Django 6.0.3 on 2026-04-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("linguagem", "Linguagem de Programação"),
                            ("framework", "Framework"),
                            ("base_dados", "Base de Dados"),
                            ("ferramenta", "Ferramenta"),
                            ("devops", "DevOps"),
                            ("outro", "Outro"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="tecnologias/"),
                ),
                ("urlSite", models.URLField(blank=True)),
                (
                    "nivel",
                    models.IntegerField(
                        choices=[
                            (1, "1 - Básico"),
                            (2, "2 - Elementar"),
                            (3, "3 - Intermédio"),
                            (4, "4 - Avançado"),
                            (5, "5 - Especialista"),
                        ]
                    ),
                ),
                ("aspetosRelavantes", models.TextField(blank=True)),
            ],
        ),
    ]
