# Generated by Django 6.0.3 on 2026-04-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_categoriacompetencia_competencia"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tfc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("aluno", models.CharField(max_length=255)),
                ("orientador", models.CharField(blank=True, max_length=255)),
                ("ano", models.IntegerField()),
                ("url_relatorio", models.URLField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("imagem", models.ImageField(blank=True, null=True, upload_to="tfcs/")),
                (
                    "classificacao",
                    models.IntegerField(
                        choices=[
                            (1, "1 - Pouco interessante"),
                            (2, "2 - Interessante"),
                            (3, "3 - Moderadamente interessante"),
                            (4, "4 - Muito interessante"),
                            (5, "5 - Extremamente interessante"),
                        ],
                        default=3,
                    ),
                ),
                (
                    "licenciatura",
                    models.ManyToManyField(
                        related_name="tfcs", to="portfolio.licenciatura"
                    ),
                ),
                (
                    "tecnologia",
                    models.ManyToManyField(
                        related_name="tfcs", to="portfolio.tecnologia"
                    ),
                ),
            ],
        ),
    ]
