# Generated by Django 6.0.3 on 2026-04-04 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_tfc"),
    ]

    operations = [
        migrations.CreateModel(
            name="Formacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("instituicao", models.CharField(blank=True, max_length=255)),
                ("data_inicio", models.DateField(blank=True, null=True)),
                ("data_conclusao", models.DateField(blank=True, null=True)),
                (
                    "certificado",
                    models.ImageField(blank=True, upload_to="certificados/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("descricao", models.TextField()),
                ("urlVideo", models.URLField(blank=True)),
                ("imagem", models.ImageField(blank=True, upload_to="projetos/")),
                ("conceitos", models.TextField(blank=True)),
                ("urlGithub", models.URLField(blank=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("UC", "Unidade Curricular"), ("PESSOAL", "Pessoal")],
                        max_length=10,
                    ),
                ),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        blank=True, related_name="projetos", to="portfolio.tecnologia"
                    ),
                ),
                (
                    "uc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projetos",
                        to="portfolio.unidadecurricular",
                    ),
                ),
            ],
        ),
    ]
