# Generated by Django 6.0.3 on 2026-04-04 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_formacao_projeto"),
    ]

    operations = [
        migrations.CreateModel(
            name="MakingOf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("descricao", models.TextField()),
                ("justificacao", models.TextField()),
                ("erros", models.TextField(blank=True)),
                ("correcoes", models.TextField(blank=True)),
                ("usoIa", models.TextField(blank=True)),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="makingof/"),
                ),
                ("dataRegisto", models.DateField(auto_now_add=True)),
                (
                    "competencia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="makingof",
                        to="portfolio.competencia",
                    ),
                ),
                (
                    "licenciatura",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="makingof",
                        to="portfolio.licenciatura",
                    ),
                ),
                (
                    "projeto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="makingof",
                        to="portfolio.projeto",
                    ),
                ),
                (
                    "tfc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="makingof",
                        to="portfolio.tfc",
                    ),
                ),
                (
                    "uc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="makingof",
                        to="portfolio.unidadecurricular",
                    ),
                ),
            ],
        ),
    ]
