# Generated by Django 6.0.3 on 2026-04-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_makingof"),
    ]

    operations = [
        migrations.AlterField(
            model_name="licenciatura",
            name="duracao",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="licenciatura",
            name="objetivos",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="licenciatura",
            name="urlSite",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
