# Generated by Django 6.0.3 on 2026-04-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_alter_licenciatura_duracao_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="makingof",
            name="competencia",
        ),
        migrations.RemoveField(
            model_name="makingof",
            name="licenciatura",
        ),
        migrations.RemoveField(
            model_name="makingof",
            name="projeto",
        ),
        migrations.RemoveField(
            model_name="makingof",
            name="tfc",
        ),
        migrations.RemoveField(
            model_name="makingof",
            name="uc",
        ),
        migrations.AddField(
            model_name="makingof",
            name="entidade",
            field=models.CharField(
                choices=[
                    ("licenciatura", "Licenciatura"),
                    ("uc", "Unidade Curricular"),
                    ("docente", "Docente"),
                    ("projeto", "Projeto"),
                    ("tecnologia", "Tecnologia"),
                    ("tfc", "TFC"),
                    ("competencia", "Competência"),
                    ("categoria_competencia", "Categoria Competência"),
                    ("formacao", "Formação"),
                    ("makingof", "MakingOf"),
                    ("geral", "Geral"),
                ],
                default="geral",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="makingof",
            name="descricao",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="makingof",
            name="justificacao",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="descricao",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="ano",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="apresentacao",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="ects",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="programa",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="semestre",
            field=models.IntegerField(blank=True),
        ),
    ]
