# Generated by Django 6.0.3 on 2026-04-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0008_remove_makingof_competencia_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tfc",
            name="aluno",
        ),
        migrations.RemoveField(
            model_name="tfc",
            name="orientador",
        ),
        migrations.AddField(
            model_name="tfc",
            name="alunos",
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="tfc",
            name="areas",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="tfc",
            name="orientadores",
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="tecnologia",
            name="tipo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("linguagem", "Linguagem de Programação"),
                    ("framework", "Framework"),
                    ("base_dados", "Base de Dados"),
                    ("ferramenta", "Ferramenta"),
                    ("devops", "DevOps"),
                    ("outro", "Outro"),
                ],
                max_length=50,
            ),
        ),
    ]
