# Generated by Django 6.0.3 on 2026-04-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0010_alter_tecnologia_nivel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tecnologia",
            name="nivel",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "1 - Básico"),
                    (2, "2 - Elementar"),
                    (3, "3 - Intermédio"),
                    (4, "4 - Avançado"),
                    (5, "5 - Especialista"),
                ],
                default=3,
            ),
        ),
    ]
