# Generated by Django 6.0.3 on 2026-04-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0011_alter_tecnologia_nivel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tfc",
            name="orientadores",
        ),
        migrations.AddField(
            model_name="tfc",
            name="orientadores",
            field=models.ManyToManyField(
                blank=True, related_name="tfcs", to="portfolio.docente"
            ),
        ),
    ]
