# Generated by Django 6.0.3 on 2026-04-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0012_remove_tfc_orientadores_tfc_orientadores"),
    ]

    operations = [
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("hackathon", "Hackathon"),
                            ("voluntariado", "Voluntariado"),
                            ("competicao", "Competição"),
                            ("conferencia", "Conferência"),
                            ("workshop", "Workshop"),
                            ("outro", "Outro"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "papel",
                    models.CharField(
                        choices=[
                            ("participante", "Participante"),
                            ("organizador", "Organizador"),
                            ("voluntario", "Voluntário"),
                            ("orador", "Orador"),
                        ],
                        max_length=50,
                    ),
                ),
                ("descricao", models.TextField(blank=True)),
                ("data", models.DateField(blank=True, null=True)),
                ("local", models.CharField(blank=True, max_length=255)),
                ("url", models.URLField(blank=True)),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="eventos/"),
                ),
                (
                    "competencias",
                    models.ManyToManyField(
                        blank=True, related_name="eventos", to="portfolio.competencia"
                    ),
                ),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        blank=True, related_name="eventos", to="portfolio.tecnologia"
                    ),
                ),
            ],
        ),
    ]
