# Generated by Django 6.0.3 on 2026-04-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0013_evento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="makingof",
            name="entidade",
            field=models.CharField(
                choices=[
                    ("licenciatura", "Licenciatura"),
                    ("uc", "Unidade Curricular"),
                    ("docente", "Docente"),
                    ("projeto", "Projeto"),
                    ("tecnologia", "Tecnologia"),
                    ("tfc", "TFC"),
                    ("competencia", "Competência"),
                    ("categoria_competencia", "Categoria Competência"),
                    ("formacao", "Formação"),
                    ("evento", "Evento"),
                    ("makingof", "MakingOf"),
                    ("geral", "Geral"),
                ],
                default="geral",
                max_length=50,
            ),
        ),
    ]
